In [9]:
import numpy as np 
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
for row in a:
    print(row)
    for cell in row:
        print(cell)

[0 1 2]
0
1
2
[3 4 5]
3
4
5
[6 7 8]
6
7
8
[ 9 10 11]
9
10
11


In [12]:
for i in np.nditer(a,order="c"):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [16]:
for i in np.nditer(a,order='F'):
    print(i)
    

0
3
6
9
1
4
7
10
2
5
8
11


In [21]:
for x in np.nditer(a,order="F",flags=["external_loop"]):
    print(x)
    

[0 3 6 9]
[ 1  4  7 10]
[ 2  5  8 11]


In [24]:
for x in np.nditer(a,op_flags=["readwrite"]):
    x[...]=x*x

In [25]:
a

array([[    0,     1,    16],
       [   81,   256,   625],
       [ 1296,  2401,  4096],
       [ 6561, 10000, 14641]])

In [2]:
# full((shape),value)
import numpy as np 
f=np.full((3,3),5)
print(f)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [4]:
r=np.arange(0,10,2)
print(r)

[0 2 4 6 8]


In [5]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
y=np.array([2.3,4.2,8.6])
y1=y.astype(int)
print(y1)

[2 4 8]


In [9]:
print(y1+5)
print(y1*3)
print(y1**3)

[ 7  9 13]
[ 6 12 24]
[  8  64 512]


In [13]:
n=np.array([12,35,68,852,223])
print(n[0:4])

[ 12  35  68 852]


In [14]:
# fancy indexing
print(n[[0,1,4]])

[ 12  35 223]


In [17]:
print(n[n>50])

[ 68 852 223]


In [23]:
n1=np.array([[1,7,9,44],[46,98,37,48]])
print(n1.ravel())
print(n1)

[ 1  7  9 44 46 98 37 48]
[[ 1  7  9 44]
 [46 98 37 48]]


In [ ]:
print(n1.flatten())
print(n1)

[ 1  7  9 44 46 98 37 48]
[[ 1  7  9 44]
 [46 98 37 48]]


In [31]:
print(np.insert(n,3,50))
print(np.insert(n1,1,[2,4],axis=None))

[ 12  35  68  50 852 223]
[ 1  2  4  7  9 44 46 98 37 48]


In [2]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90])
new_arr=np.delete(arr,3)
print(arr)
print(new_arr)

[10 20 30 40 50 60 70 80 90]
[10 20 30 50 60 70 80 90]


In [5]:
n=np.array([[1,7,9],[6,45,78]])
new=np.delete(n,0,axis=0)
new

array([[ 6, 45, 78]])

In [10]:
import numpy as np
arr1=np.array([4,8,9])
arr2=np.array([23,56,89])
arr3=np.array([78,90,34])
varticaly=np.vstack((arr1,arr2,arr3))
print("varticat:",varticaly)
horizontaly=np.hstack((arr1,arr2,arr3))
print("horizontaly:",horizontaly)

varticat: [[ 4  8  9]
 [23 56 89]
 [78 90 34]]
horizontaly: [ 4  8  9 23 56 89 78 90 34]


In [13]:
""" np.split(arr,parts_number)"""
print(np.split(horizontaly,3))


[array([4, 8, 9]), array([23, 56, 89]), array([78, 90, 34])]


In [19]:
u=np.array([[45,83,56],[56,78,75]])
print(np.vsplit(u,2))
print(np.hsplit(u,1))

[array([[45, 83, 56]]), array([[56, 78, 75]])]
[array([[45, 83, 56],
       [56, 78, 75]])]


In [4]:
l=[8,9,6]
L=[]
for i in l:
    print(i*10)
    L.append(i*10)
print(L)

80
90
60
[80, 90, 60]


In [ ]:
import numpy as np 
arr=np.array([8,9,6])
result=arr*10
print(result)

[80 90 60]


Handeling Missing Values in numpy

In [6]:
# np.isnan(array)
import numpy as np 
arr=np.array([3,8,6,np.nan,67,90,np.nan,100])
print(np.isnan(arr))

[False False False  True False False  True False]


In [8]:
# np.nan_to_num(array,nan=value)
a=np.nan_to_num(arr,nan=10)
print(a)

[  3.   8.   6.  10.  67.  90.  10. 100.]


In [16]:
# Infinty
# np.isinf(array)
l=np.array([56,89,20,np.inf,78,-np.inf])
result=np.isinf(l)
print(result)
# solve(prossece one)
# l[np.isinf(l)] = 0
# print(l)
r=np.nan_to_num(l,posinf=6,neginf=0)
print(r)

[False False False  True False  True]
[56. 89. 20.  6. 78.  0.]


In [2]:
import numpy as np
a = np.linspace(0, 10, 20)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


Slicing

In [11]:
a=np.array([[2,3,5],[6,8,5],[8,5,4]])
print(a)
print(a[1,2])
print(a[0:1])
print("____")
print(a[0:2,1:2])

[[2 3 5]
 [6 8 5]
 [8 5 4]]
5
[[2 3 5]]
____
[[3]
 [8]]


In [3]:
import numpy as np 
a=np.array([[2,4,6],[45,64,3],[5,4,22]])
print(a)
for cell in a.flat:
    print(cell)

[[ 2  4  6]
 [45 64  3]
 [ 5  4 22]]
2
4
6
45
64
3
5
4
22


In [14]:
b=np.arange(30).reshape(2,15)
print(b)
print("vsplit:" ,np.vsplit(b,2))
print(np.hsplit(b,5))


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
vsplit: [array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]
[array([[ 0,  1,  2],
       [15, 16, 17]]), array([[ 3,  4,  5],
       [18, 19, 20]]), array([[ 6,  7,  8],
       [21, 22, 23]]), array([[ 9, 10, 11],
       [24, 25, 26]]), array([[12, 13, 14],
       [27, 28, 29]])]
